name: CI Pipeline with Testing and Reporting

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Required for Allure history
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Run tests and generate reports
    - name: Run tests with coverage and reporting
      run: mvn clean install -B
      env:
        MAVEN_OPTS: "-Xmx2048m"
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    
    # Upload JaCoCo coverage to Codecov (optional)
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    # Generate JaCoCo coverage report comment for PR
    - name: Add coverage to PR
      if: github.event_name == 'pull_request'
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        title: 'Code Coverage Report'
        update-comment: true
    
    # Load Allure test history from previous runs
    - name: Get Allure history
      uses: actions/checkout@v5
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Setup Allure history
      if: always()
      run: |
        if [ -d "gh-pages/allure-history" ]; then
          cp -r gh-pages/allure-history/. target/allure-results/history/
        fi
    
    # Generate Allure report
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history
        keep_reports: 20
    
    # Upload test artifacts
    - name: Upload JaCoCo coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-coverage-report
        path: |
          target/site/jacoco/
          target/site/jacoco-it/
        retention-days: 30
    
    - name: Upload Allure test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: target/allure-results/
        retention-days: 30
    
    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    
    # Deploy to GitHub Pages (optional)
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
    
    - name: Upload to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: gh-pages
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4

  # Optional: Separate job for security scanning
  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Run OWASP Dependency Check
      run: |
        mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=7
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    
    - name: Upload OWASP report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: owasp-dependency-check-report
        path: target/dependency-check-report.html
        retention-days: 30
