name: Test Reports Only

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Run tests with coverage and reporting
      run: mvn clean install -B
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    
    # JaCoCo Coverage Report for PRs
    - name: Add coverage to PR
      if: github.event_name == 'pull_request'
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        title: '🧪 Code Coverage Report'
        update-comment: true
    
    # Generate and upload Allure report
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: target/allure-results
        allure_report: allure-report
        keep_reports: 5
    
    # Upload artifacts
    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-coverage-${{ github.run_number }}
        path: target/site/jacoco/
        retention-days: 14
    
    - name: Upload Allure Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report-${{ github.run_number }}
        path: allure-report/
        retention-days: 14
    
    # Test Results Summary
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: 'Test Results'
        path: 'target/surefire-reports/*.xml,target/failsafe-reports/*.xml'
        reporter: 'java-junit'
